-d C:\Users\adell\Documents\fpga_project_5\impl\gwsynthesis\fpga_project_5.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\adell\Documents\fpga_project_5\src\fpga_project_5.cst
-cfg C:\Users\adell\Documents\fpga_project_5\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
